import { Inter } from "next/font/google";
import "./globals.css";
import NavBarComponent from "./components/NavBar/NavBarComponent";
import Provider from "./provider";
import FooterComponent from "./components/Footer/FooterComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <Provider>
           <NavBarComponent/>
          </Provider>
          {children}
          <FooterComponent/>
        </body>
      </html>
    </>
  );
}
